Ejercicio 1

In [1]:
import csv

datos_tienda = [
    {"ID": 1001, "Producto": "Laptop Gamer", "Categoria": "Computacion", "Precio": 1200000, "Stock": 15},
    {"ID": 1002, "Producto": "Mouse Inalambrico", "Categoria": "Accesorios", "Precio": 25000, "Stock": 100},
    {"ID": 1003, "Producto": "Teclado Mecanico", "Categoria": "Accesorios", "Precio": 85000, "Stock": 40},
    {"ID": 1004, "Producto": "Monitor 27 Pulgadas", "Categoria": "Computacion", "Precio": 350000, "Stock": 25},
    {"ID": 1005, "Producto": "Auriculares Bluetooth", "Categoria": "Audio", "Precio": 60000, "Stock": ""},
    {"ID": 1006, "Producto": "Silla Ergonomica", "Categoria": "Muebles", "Precio": 250000, "Stock": 10}
]

with open('productos.csv', 'w', newline='', encoding='utf-8') as archivo:
    columnas = ["ID", "Producto", "Categoria", "Precio", "Stock"]

    writer = csv.DictWriter(archivo, fieldnames=columnas)

    writer.writeheader()
    writer.writerows(datos_tienda)

print("Archivo creado exitosamente.")

Archivo creado exitosamente.

Ejercicio 2

In [2]:
import pandas as pd

df_productos = pd.read_csv("productos.csv")
#primeras 3 filas del DataFrame
print("Primeras 3 filas del DataFrame:")
df_productos.head(3)

Primeras 3 filas del DataFrame:

     ID           Producto    Categoria   Precio  Stock
0  1001       Laptop Gamer  Computacion  1200000   15.0
1  1002  Mouse Inalambrico   Accesorios    25000  100.0
2  1003   Teclado Mecanico   Accesorios    85000   40.0

In [3]:
print("ultimas 2 filas del DataFrame:")
df_productos.tail(2)

ultimas 2 filas del DataFrame:

     ID               Producto Categoria  Precio  Stock
4  1005  Auriculares Bluetooth     Audio   60000    NaN
5  1006       Silla Ergonomica   Muebles  250000   10.0

Ejercicio 3

In [4]:
df_productos.info()
#1 datos faltantes en la columna "Stock"

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         6 non-null      int64
 1   Producto   6 non-null      str
 2   Categoria  6 non-null      str
 3   Precio     6 non-null      int64
 4   Stock      5 non-null      float64
dtypes: float64(1), int64(2), str(2)
memory usage: 527.0 bytes

In [8]:
df_productos.describe()
#

                ID        Precio       Stock
count     6.000000  6.000000e+00    5.000000
mean   1003.500000  3.283333e+05   38.000000
std       1.870829  4.448895e+05   36.503424
min    1001.000000  2.500000e+04   10.000000
25%    1002.250000  6.625000e+04   15.000000
50%    1003.500000  1.675000e+05   25.000000
75%    1004.750000  3.250000e+05   40.000000
max    1006.000000  1.200000e+06  100.000000

Ejercicio 4

In [9]:
tabla_marketing = df_productos[["Producto", "Precio"]]
print(tabla_marketing)

                Producto   Precio
0           Laptop Gamer  1200000
1      Mouse Inalambrico    25000
2       Teclado Mecanico    85000
3    Monitor 27 Pulgadas   350000
4  Auriculares Bluetooth    60000
5       Silla Ergonomica   250000

In [13]:
precio = df_productos["Precio"]
print(precio)
print("tipo de dato de la columna 'Precio':", type(precio))

0    1200000
1      25000
2      85000
3     350000
4      60000
5     250000
Name: Precio, dtype: int64
tipo de dato de la columna 'Precio': <class 'pandas.Series'>

Ejercicio 5

In [14]:
capital_por_producto = df_productos["Precio"] * df_productos["Stock"]
print(capital_por_producto)

0    18000000.0
1     2500000.0
2     3400000.0
3     8750000.0
4           NaN
5     2500000.0
dtype: float64