Ejercicio 1

In [1]:
import pandas as pd
import numpy as np

# Generación de datos simulados
np.random.seed(123)

legajos_generados = ['TUP-' + str(i) for i in range(1001, 1021)]

carreras_disponibles = ['Programacion', 'Redes', 'Sistemas']

datos_academicos = {
    'Legajo': legajos_generados,
    'Carrera': np.random.choice(carreras_disponibles, 20),
    'Matematica': np.random.randint(2, 11, 20),
    'Bases_Datos': np.random.randint(2, 11, 20),
    'Algoritmos': np.random.randint(2, 11, 20)
}

df_generador = pd.DataFrame(datos_academicos)

df_generador.to_csv('notas_semestre.csv', index=False)

print('Archivo notas_semestre.csv generado con éxito.')

Archivo notas_semestre.csv generado con éxito.

In [2]:
import pandas as pd

df_notas = pd.read_csv("notas_semestre.csv")

In [3]:
df_notas.set_index("Legajo", inplace=True)

In [4]:
df_notas.head()

               Carrera  Matematica  Bases_Datos  Algoritmos
Legajo
TUP-1001      Sistemas           5            7           9
TUP-1002         Redes           6            8           3
TUP-1003      Sistemas           2            4           7
TUP-1004      Sistemas           2            3           9
TUP-1005  Programacion           6           10           4

Ejercicio 2

In [5]:
df_notas.describe()

       Matematica  Bases_Datos  Algoritmos
count    20.00000    20.000000     20.0000
mean      5.50000     6.000000      5.6500
std       2.50263     2.316985      2.5808
min       2.00000     2.000000      2.0000
25%       3.75000     4.000000      3.0000
50%       5.50000     6.000000      5.0000
75%       6.50000     8.000000      7.2500
max      10.00000    10.000000     10.0000

In [6]:
df_notas.iloc[9]

Carrera        Redes
Matematica         6
Bases_Datos        8
Algoritmos         3
Name: TUP-1010, dtype: object

In [7]:
df_notas.iloc[0:3,0:2]

           Carrera  Matematica
Legajo
TUP-1001  Sistemas           5
TUP-1002     Redes           6
TUP-1003  Sistemas           2

Ejercicio 3

In [8]:
df_notas.loc["TUP-1005","Bases_Datos"] = 9
print(df_notas.loc["TUP-1005","Bases_Datos"])

9

In [9]:
df_notas.loc["TUP-1018","Bases_Datos"] = 7
print(df_notas.loc["TUP-1018","Bases_Datos"])

7

In [10]:
df_notas.loc[["TUP-1005","TUP-1018"]]

               Carrera  Matematica  Bases_Datos  Algoritmos
Legajo
TUP-1005  Programacion           6            9           4
TUP-1018      Sistemas           6            7           5

Ejercicio 4

In [11]:
mascara = (
    (df_notas["Carrera"] == "Programacion")
    &
    (df_notas["Algoritmos"] >= 8)
)

In [12]:
df_destacados = df_notas[mascara]

In [13]:
print(df_destacados)

               Carrera  Matematica  Bases_Datos  Algoritmos
Legajo
TUP-1017  Programacion           5            8           8

Ejercicio 5

In [15]:
df_redes = (df_notas.loc[df_notas["Carrera"] == "Redes"])

In [22]:
matematica_redes = df_redes["Matematica"]
print(matematica_redes)
promedio = matematica_redes.mean()
print(promedio)

Legajo
TUP-1002     6
TUP-1008     5
TUP-1010     6
TUP-1012     4
TUP-1014    10
TUP-1016     9
TUP-1020     3
Name: Matematica, dtype: int64
6.142857142857143