Ejercicio 1

In [18]:
import pandas as pd
import numpy as np
np.random.seed(26)
cantidad_pedidos = 500
fechas_despacho = pd.to_datetime('2025-08-01') + pd.to_timedelta(np.random.randint(0, 60,
cantidad_pedidos), unit='D')
fechas_llegada = fechas_despacho + pd.to_timedelta(np.random.randint(2, 25, cantidad_pedidos), unit='D')
datos_bodega = {
 'ID_Remito': np.arange(8000, 8000 + cantidad_pedidos),
 'Varietal': np.random.choice(['Malbec', 'Cabernet Franc', 'Chardonnay', 'Syrah'], cantidad_pedidos),
 'Cajas_Enviadas': np.random.randint(10, 200, cantidad_pedidos),
 'Precio_Por_Caja': np.random.randint(15000, 45000, cantidad_pedidos),
 'Fecha_Despacho': fechas_despacho.astype(str),
 'Fecha_Llegada': fechas_llegada.astype(str)
}
df_bodega = pd.DataFrame(datos_bodega)
df_bodega.to_csv('logistica_bodega.csv', index=False)
print('Archivo logistica_bodega.csv generado exitosamente.')

Archivo logistica_bodega.csv generado exitosamente.

Ejercicio 2

In [19]:
import pandas as pd
df = pd.read_csv('logistica_bodega.csv')

In [20]:
df["valor_total_envio"] = df['Cajas_Enviadas'] * df['Precio_Por_Caja']
df.head(3)

,ID_Remito,Varietal,Cajas_Enviadas,Precio_Por_Caja,Fecha_Despacho,Fecha_Llegada,valor_total_envio
0,8000,Malbec,133,33311,2025-09-23,2025-10-06,4430363
1,8001,Cabernet Franc,199,23451,2025-08-07,2025-08-09,4666749
2,8002,Chardonnay,162,23261,2025-09-18,2025-10-12,3768282

Ejercicio 3

In [26]:
df["Fecha_Despacho"] = pd.to_datetime(df["Fecha_Despacho"])
df["Fecha_Llegada"] = pd.to_datetime(df["Fecha_Llegada"])

In [27]:
df["Dias_En_Transito"] = (df["Fecha_Llegada"]- df["Fecha_Despacho"]).dt.days
df.head(3)

,ID_Remito,Varietal,Cajas_Enviadas,Precio_Por_Caja,Fecha_Despacho,Fecha_Llegada,valor_total_envio,Dias_En_Transito
0,8000,Malbec,133,33311,2025-09-23,2025-10-06,4430363,13
1,8001,Cabernet Franc,199,23451,2025-08-07,2025-08-09,4666749,2
2,8002,Chardonnay,162,23261,2025-09-18,2025-10-12,3768282,24

Ejercicio 4

In [30]:
def evaluar_calidad_logistica(dias):
    if dias <= 7:
        return "Optimo"
    elif dias <= 15:
        return "Aceptable"
    else:
        return "Riesgo de temperatura"

In [31]:
df["Estado_Calidad"] = (df["Dias_En_Transito"]).apply(evaluar_calidad_logistica)

In [32]:
print(df["Estado_Calidad"].value_counts())

Estado_Calidad
Riesgo de temperatura    194
Aceptable                180
Optimo                   126
Name: count, dtype: int64

Ejercicio 5

In [33]:
mascara = (
    (df["Varietal"] == "Malbec")
    &
    (df["Estado_Calidad"] == "Riesgo de Temperatura")
)

In [34]:
df_malbec_riesgo = df[mascara]

print(df_malbec_riesgo)

Empty DataFrame
Columns: [ID_Remito, Varietal, Cajas_Enviadas, Precio_Por_Caja, Fecha_Despacho, Fecha_Llegada, valor_total_envio, Dias_En_Transito, Estado_Calidad]
Index: []

In [37]:
total_riesgo = (
    df_malbec_riesgo["valor_total_envio"].sum()
)

print(
    f"Pesos en Malbec en riesgo por demoras logísticas: ${total_riesgo}"
)

Pesos en Malbec en riesgo por demoras logísticas: $0